#!/usr/bin/env bash
# A Bash script that lists all processes in a user-friendly, hierarchical format

ps -eo user,lstart,cmd --forest | awk 'NR==1 {print "USER STARTED CMD"; next} {printf "%s %s %s %s %s %s %s\n", $1, $2, $3, $4, $5, $6, substr($0, index($0,$8))}'
