#!/usr/bin/env bash
# Display running processes with exact format: 39 characters total

ps -eo user,lstart,cmd --no-headers | head -n 1 | awk '
BEGIN { print "USER STARTED CMD" }
{
    # USER = $1, TIME = $5:$6:$7, CMD = $8
    printf "%s %s:%s:%s %s\n", $1, $5, $6, $7, $8
}'
