#!/usr/bin/env bash
# Infinite loop printing "To infinity and beyond" every 2 sec
# On SIGTERM prints "I am invincible!!!" and continues

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
