#!/usr/bin/env bash
# Prints numbers 1 to 20; adds "bad luck" messages for specific numbers using case

count=1
while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac
  ((count++))
done
